### ISSUE TITLE
[META] Open referral: Expose API

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_directories#123]
- [x] break this up into smaller issues @ekes 
- [x] new issue for service endpoint (5)
- [x] new issue for taxonomy endpoint (5)
- [x] new issue for organisation (3)
- [x] new issue for location (3)
- [x] new issue for enable search / filtering on endpoints. (5)

**Comment by ekes** [comment]
- #125 Initial architecture 
- #124 Additional organisation entity
- #126 Taxonomy/Vocabulary endpoints
- #127 Using the taxonomy to filter the endpoint defined in the initial structure
- #128 Location endpoint
- #129 Organisation endpoint

Future planning

- #130 Reviews

**Comment by ekes** [comment]
Tasks done. There are issues for further work.
